mybatis:
  datasource:
    basename:
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useSSL=true
      username: root
      password: 123456
      driverClass: com.mysql.jdbc.Driver
server:
  port: 8090